browser=firefox
OrangeHRMurl = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
FbRegURL=
username=Admin
password=admin123


drivername=com.microsoft.sqlserver.jdbc.SQLServerDriver
dbURL=jdbc:sqlserver://localhost:1433;databaseName=master;encrypt=false;trustServerCertificate=true;
dbUsername=sa
dbPassword=MyStrong@Pass123

baseURI=http://localhost:9090/

bearertoken=MyStrong@Pass123

screenShotLogFilePath=./Reports/WordLogs
	
HSBC_Trust_Token=HSBC_Trust_Token